Added notifys & removed subshell calls

diff --git a/testcode/x1bashrc b/testcode/x1bashrc
--- a/testcode/x1bashrc
+++ b/testcode/x1bashrc
@@ -1,3 +1,35 @@
+# Trap DEBUG to exec before commands, only in newer bash
+# this is unsupported in bash3, DEBUG trap execs after
+# https://superuser.com/questions/175799/does-bash-have-a-hook-that-is-run-before-executing-a-command
+#newer on github: https://github.com/rcaloras/bash-preexec
+X1_PRECNT=0         #command counter to know if cmd was blank (no increment)
+X1_CMDCNT=0
+X1_PRETIM=$SECONDS  #time tracker
+X1_DELAY='3'       #Min cmd time to print
+# X1_TIMING='false' #do a check first of bash version and notify-send
+# installed
+preexec_invoke() {
+    [ -n "$COMP_LINE" ] && return                     #ignore auto-complete
+    [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return #ignore PS1 func
+    X1_PRECMD=$BASH_COMMAND  #store command
+    ((X1_PRECNT++))          #increment counter, to know empty prompt
+    X1_PRETIM=$SECONDS       #store time of command
+    echo -e "\e]0;"; echo -n $BASH_COMMAND; echo -ne "\007" #set win title
+}
+trap 'preexec_invoke' DEBUG #trap DEBUG execs before every 'simple' command
+
+x1alert(){
+    case "$1" in "vi"*) ;;
+	*)
+	    #--hint=int:transient:1 # add and then isn't persistent
+	    # can maybe make 2 versions, really long ones will persist?
+	    notify-send --urgency=low \
+	                -i "$([ $? = 0 ] && echo terminal || echo error)" \
+			 "$1 took $2"
+	;;
+    esac
+}
+
 # PS1 setting function, features:
 # print in color if available
 # first print user@host:time/cmd time
@@ -29,35 +61,36 @@ else
     X1_ECOL=''
 fi
 
-if [ -z "$HISTTIMEFORMAT" ] || [ "$HISTTIMEFORMAT" = '%s ' ]; then
-    HISTCONTROL=''
-    HISTTIMEFORMAT='%s '
-    X1_CMDTIME=$(date +%s)
-    X1_DELAY='30'
-    X1_CMDCNT=$(history 1 |cut -f2 -d' ')
-else
-    #Already set, don't overwrite
-    echo 'No X1PS1 timing info, HISTTIMEFORMAT already set'
-    X1_TIMING='false'
-fi
  
-X1FormTime(){ #Convert sec to min sec for display
-    local min=$(($1 / 60))
-    local sec=$(($1 - ($min * 60) ))
-    sec=$(printf '%02d' $sec)
-    if [ "$min" = "0" ]; then
-	echo "$X1_SCOLG0${min}m${sec}s$X1_ECOL" #mins = 0, green
-    else 
-	echo "$X1_SCOLY${min}m${sec}s$X1_ECOL" #mins != 0, yellow
+X1FormTime(){ #Convert sec to [hr]+min+sec for display
+    #This can be called w/o subshell if use printf -v
+    local hr=$(( $1/3600 ))
+    local min=$(( ($1/60) - ($hr*3600) ))
+    local sec=$(( $1 - ($min*60) ))
+
+    if [ "$hr" != "0" ]; then                              #hr > 0, red
+	printf -v X1_CMDTIME "%dh%02dm%02ds" $hr $min $sec
+	x1alert "$X1_PRECMD" "$X1_CMDTIME"
+	printf -v X1_CMDTIME "${X1_SCOLR}$X1_CMDTIME$X1_ECOL"
+    elif [ "$min" != "0" ]; then                           #mins > 0, yellow
+	printf -v X1_CMDTIME "%dm%02ds" $min $sec
+	x1alert "$X1_PRECMD" "$X1_CMDTIME"
+	printf -v X1_CMDTIME "${X1_SCOLY}$X1_CMDTIME$X1_ECOL"
+    else                                                   #mins = 0, green
+	printf -v X1_CMDTIME "0m%02ds" $sec
+	x1alert "$X1_PRECMD" "$X1_CMDTIME"
+	printf -v X1_CMDTIME "${X1_SCOLG0}$X1_CMDTIME$X1_ECOL"
     fi
 }
 
 get_PS1() {
 # Idea for git branch inclusion: replace user@host if we're on a git
 #   branch, or maybe just user since host tells us if we're ssh'ing
+#   or maybe dynamicly can replace host if git branch is really long
+#   can also omit time if not delayed
 
-    local stat="$?" #get last exits status
-    if [ $stat = 0 ]; then #set exit status color
+    local stat="$?"        # get last exits status
+    if [ $stat = 0 ]; then # set exit status color
         stat=""
     else
 	stat="${X1_SCOLR}${stat}${X1_ECOL}"
@@ -65,20 +98,13 @@ get_PS1() {
 
     local x1time="$X1_SCOLG0\A$X1_ECOL" #Displayed time, default green clock
     if [ -z "$X1_TMING" ]; then
-        #check against last prompt first (only 1 subshell call)
-        #and for empty command (also 1 subshell call)
-        if [ $(($(date +%s) - $X1_CMDTIME)) -gt $X1_DELAY ] && \
-           [ "$(history 1 |cut -f2 -d' ')" != "$X1_CMDCNT" ]; then
+        if [ $(($SECONDS - $X1_PRETIM)) -gt $X1_DELAY ] && \
+           [ "$X1_PRECNT" != "$X1_CMDCNT" ]; then
 
-	    X1_CMDTIME=$(date +%s)
-	    local x1tmp=$(history 1 |cut -f4 -d' ') #actual
-	    if [ $(($X1_CMDTIME - $x1tmp)) -gt $X1_DELAY ]; then
-		x1tmp=$(($X1_CMDTIME - $x1tmp))
-		x1time="$(X1FormTime $x1tmp)" #color time-dependent
-        fi; fi
-        X1_CMDTIME=$(date +%s)                #reset prompt timer
-        X1_CMDCNT=$(history 1 |cut -f2 -d' ') #reset cmd counter
-    fi
+	    X1FormTime $(($SECONDS -$X1_PRETIM))
+	    x1time=$X1_CMDTIME
+            X1_CMDCNT=$X1_PRECNT
+    fi; fi
 
     #get the pwd split into dirs
     local IFS="/"
@@ -92,8 +118,7 @@ get_PS1() {
     local HPATH=()
     read -ra HPATH <<< "$HOME"
 
-    local j=0
-    local same=0
+    local j=0; local same=0
     if [ "${#HPATH[@]}" -gt 0 ]; then
 	for i in "${HPATH[@]}"; do
 	    if [ "$i" != "${PARTS[$j]}" ]; then 
@@ -136,8 +161,10 @@ get_PS1() {
 	plen=$(($lenmax*$plast +${#cdir}))
 	if [ $plen -gt 30 ]; then
 	    lenmax=$(($lenmax -1))
-	fi
-    fi
+            if [ "${#cdir}" -gt 10 ]; then
+                cdir="${cdir::3}[~]${cdir:$((${#cdir}-5))}"
+                #cdir="${cdir::3}$X1_ECOL[~]$X1_SCOLB${cdir:$((${#cdir}-5))}"
+    fi; fi; fi
 
     #now set the directory to display in PS1
     local dispdir=""
