Add git/conda support, ssh alerts

diff --git a/testcode/x1bashrc b/testcode/x1bashrc
--- a/testcode/x1bashrc
+++ b/testcode/x1bashrc
@@ -1,43 +1,89 @@
-# PS1 setting script, features:
+#  PS1 setting script, features:
+
 ## print in color (if available)
+## Order of precedence to display: opt1/opt2 means opt1
+## has priority if present. '' means opt2 is nothing.
+
+#  Regular use:
+##   user@host|cmd_time/clock|pwd$exit/''>
+
 ## first print user@host (green):
 ##   host color is bold if SSH session.
-## time (green) || cmd_time (green|yellow|red):
-##   clock time or cmd_time (if cmd_time>30s).
-##   cmd_time colors: green(30-59s||any editor/ssh), 
-##   yellow(1-59m), red(>1hr). if cmd_time > 1min, GUI 
-##   alert sent, > 10min peristent alert.
+## cmd_time (green|yellow|red) || clock (green):
+##   clock time or cmd_time (if cmd_time > 30s).
+##   cmd_time colors: green(30-59s||exemptions in 
+##   x1_formTime), yellow(1-59m), red(>1hr). If 
+##   cmd_time > 1min and on alert list in x1_formTime,
+##   a GUI alert is sent, > 10min alert is peristent.
 ## path (blue):
 ##   print abbreviated path that dynamically abbreviates 
 ##   the dir names to be shorter the longer the total path.
+##   The pwd is shortened to only the current directory
+##   inside tmux.
 ## exit status (red): 
 ##   print the last exit status at the end if != 0.
 
+#  Git & Conda environments:
+## If a conda env is active or in a git repo then the
+##   username is not displayed and the clock is turned off.
+##   cmd_time still appears if > 30s. The git repo is 
+##   displayed after the host with the color in the 
+##   following order of precedence: red for dirty, yellow 
+##   for clean but untracked files present, cyan for clean
+##   but ahead/behind of remote, green for clean.
+##   The conda env is displaed where the user would be.
+##   (condaenv)@host(branchname)|cmd_time|/''pwd$exit/''>
+
 # Non-PS1 features:
 ## Set window title to last cmd
-## suggested LAST line in .bashrc to set the window title:
-#echo -ne "\e];fresh term\007" #set window title
 
-# bug?: if last command printed cmd_time then when doing an 
-#   autocomplete where it lists options, the prompt 
-#   displays the previous cmd time. 
-# reason: This is because PS1 isn't redrawn! beyond the 
-#   scope of this script to fix.
 
+shopt -s extglob    # for pattern matching
 X1_PRECNT=0         # counter to see if cmd was blank 
 X1_CMDCNT=0         # previous count
 X1_PRETIM=$SECONDS  # time tracker
-X1_DELAY='30'       # Minimum cmd time (in secs) to print
-X1_TIMING=''        # set to false to turn off timing
-X1_ALERTS=''        # set to false to turn off timing alerts
-shopt -s extglob    # for pattern matching
 
-if [ -z "$X1_TIMING" ]; then
+# User configurable settings, can set here to permanently
+# change settings, or can do `SETTING=false` after script
+# is sourced to temporarily turn off for that shell
+X1_COLORS=true      # set to false to turn off colors
+X1_TIMING=true      # set to false to turn off cmd timing
+X1_DELAY='20'       # minimum cmd time (in secs) to print
+X1_GITSTAT=true     # whether to show git branch, useful
+                    # to turn off when `git status` is slow
+X1_ALERTS=true      # set false to turn off GUI time alerts
+X1_SSHALERT=false   # whether to try to send alerts over SSH
+X1_USER='unameHere' # username on client machine for remote
+		    # alerts, must be keygen ssh connection
+X1_SSHPORT='22'     # ssh port for client machine
+
+
+if $X1_TIMING; then
+
+    if $X1_ALERTS && $X1_SSHALERT && [ -n "$SSH_CLIENT" ]; then
+	# this logic assumes only 1 level of ssh tunnel deep
+	X1_CLIENTIP=$(echo $SSH_CLIENT |cut -f1 -d' ')
+
+	ssh -o BatchMode=yes -o ConnectTimeout=2 $X1_USER@$X1_CLIENTIP \
+	    -p $X1_SSHPORT 'notify-send &>/dev/null; exit $?' &>/dev/null
+
+	X1_SSHALERT=$?
+
+	if [ "$X1_SSHALERT" = '1' ]; then
+	    X1_SSHALERT=true
+	elif [ "$X1_SSHALERT" = '127' ]; then
+	    echo "SSH client: $X1_USER@$X1_CLIENTIP,"
+	    echo "  did not have notify-send installed"
+	    X1_SSHALERT=false
+	else
+	#elif [ "$X1_SSHALERT" = '255' ]; then
+	    echo "Unable to establish keygen ssh connection"
+	    echo "with $X1_USER@$X1_CLIENTIP, GUI alerts diabled"
+	    X1_SSHALERT=false
+    fi; fi
 
     notify-send &>/dev/null  # check if GUI alerts installed
-    if [ $? -eq 127 ]; then
-	X1_ALERTS='false'
-    fi
+    [ $? -ne 1 ] && ! $X1_SSHALERT && X1_ALERTS=false
 
     x1_preexec() {
 	# command to run before every 'simple' command, tracks cmd stats
@@ -64,16 +110,13 @@ if [ $? -eq 0 ]; then
     X1_COLB='\[\e[1;34m\]'   # blue
     X1_COLR='\[\e[1;31m\]'   # red
     X1_ECOL='\[\e[00m\]'     # end color
-else
-    X1_COLG=''; X1_COLG0=''
-    X1_COLC=''; X1_COLB=''
-    X1_COLR=''; X1_ECOL=''
-    X1_COLY=''
 fi
 
 x1_formTime(){ 
     # Convert sec to hr+min or min+sec for display
-    # Sends GUI alert if time > 1min but not for most editors
+    # Sends GUI alert if time > 1min but not for the cmds in
+    # the 'case' section. List currently contains: 
+    #   vi(m), emacs, nano, pico, gedit, ssh, tmux, less
     # alert is persistant (must be cleared) if time > 10 min
     # alert is transient (cleared after fades) for < 10 min
     #
@@ -82,7 +125,7 @@ x1_formTime(){
     #
     # @returns
     # X1_CMDTIME (str): stores output in this global
-    #   green for editors and < 1 min
+    #   green for < 1 min and exemptions
     #   yellow for 1-59 min
     #   red for > 1 hour
 
@@ -107,19 +150,38 @@ x1_formTime(){
 	printf -v X1_CMDTIME "%dh%02dm" $hr $min
     fi
 
-    # send alert if needed and check for editor | ssh
-    if [ -z "$X1_ALERTS" ] && [ $x1alertlvl -gt 0 ]; then
-    case "$X1_PRECMD" in 
-	ssh?( *)|vi?(m)?( *)|nano?( *)|pico?( *)|gedit?( *))
-             # ignore editors + ssh
-	    x1col="$X1_COLG0"           # + color them green
-	;;
-	*)
-	    notify-send --hint=int:transient:$x1alertlvl --urgency=low \
-	                -i "$([ $? = 0 ] && echo terminal || echo error)" \
-			 "$X1_PRECMD took $X1_CMDTIME"
-	;;
+    if $X1_ALERTS; then
+    case "$X1_PRECMD" in # check alert lists
+
+	# list for GUI alerts: (c)make, *.(sh|x|py),
+	#  (i)python & shells (non-interactive),
+        #  SECONDS= for testing
+	?(c)make?( *)|?(ba|da|z)sh@( *)|?(i)python@( *)|\
+	+([-a-zA-Z0-9_./()]).@(?(ba|z|c)sh|x|py)|\
+	'SECONDS='*);;
+
+	# list for no GUI alerts & green color always
+	vi?(m)?( *)|nano?( *)|pico?( *)|gedit?( *)|emacs?( *)|\
+	ssh?( *)|tmux?( *)|less?( *)|man?( *)|bc?( *)|htop?( *)|\
+	gdb?(-ia)?( *)|vimdiff?( *)|tail?( *)|gnuplot?( *))
+	    x1alertlvl=0
+	    x1col="$X1_COLG0";;
+
+	*) # defaults, no alert but keep color
+	    x1alertlvl=0;;
     esac; fi
+
+    # send alert if needed 
+    if [ $x1alertlvl -gt 0 ]; then
+	if $X1_ALERTS && ! $X1_SSHALERT; then
+	    notify-send --hint=int:transient:$x1alertlvl --urgency=low \
+			-i terminal "$X1_PRECMD took $X1_CMDTIME"
+	elif $X1_ALERTS && $X1_SSHALERT; then
+	    local notecmd="notify-send --hint=int:transient:$x1alertlvl"
+	    notecmd="$notecmd --urgency=low -i network"
+	    notecmd="$notecmd '$X1_PRECMD @$HOSTNAME took $X1_CMDTIME'"
+	    ssh $X1_USER@$X1_CLIENTIP -p $X1_SSHPORT "$notecmd"
+    fi; fi
 
     # store colored output in X1_CMDTIME
     printf -v X1_CMDTIME "$x1col$X1_CMDTIME$X1_ECOL"
@@ -181,43 +243,77 @@ x1_PWD() {
 }
 
 x1_get_PS1() {
-# Idea for git branch inclusion: replace user@host if we're on a git
-#   branch, or maybe just user since host tells us if we're ssh'ing
-#   or maybe dynamicly can replace host if git branch is really long
-#   can also omit time if not cmd_time
+    # Function that sets PS1
 
-    local stat="$?"        # get last exits status
-    if [ $stat = 0 ]; then # set exit status color
+    # Get last exit value + color
+    local stat="$?"
+    if [ $stat = 0 ]; then
         stat=""
     else
-	stat="${X1_COLR}${stat}${X1_ECOL}"
+        stat="${X1_COLR}${stat}${X1_ECOL}"
     fi
 
-    local x1time="$X1_COLG0\A$X1_ECOL" #Displayed time, default green clock
-    if [ -z "$X1_TMING" ]; then
+    # Find if last cmd took > $X1_DELAY
+    local x1time=''
+    local gsep="$X1_COLG0|$X1_ECOL"             # green vert
+    if $X1_TIMING; then
         if [ $(($SECONDS - $X1_PRETIM)) -gt $X1_DELAY ] && \
            [ "$X1_PRECNT" != "$X1_CMDCNT" ]; then
 
 	    x1_formTime $(($SECONDS -$X1_PRETIM))
-	    x1time=$X1_CMDTIME
+	    x1time="$X1_CMDTIME$gsep"
 	fi
 	X1_CMDCNT=$X1_PRECNT #update outside if[] for ctrl-c
     fi
 
-    X1_DISPPWD=''
-    x1_PWD "$PWD"
 
-    #check if we're in an ssh session
-    if [ -n "$SSH_CLIENT" ]; then
-	local host="$X1_COLG\h$X1_ECOL" #bold
+    # Check git status (porcelain), show branch & top level untracked
+    if $X1_GITSTAT; then
+	local gitstat="$(git status -b -unormal --porcelain 2>/dev/null)"
     else
-	local host="$X1_COLG0\h$X1_ECOL"
+	local gitstat=''
+    fi
+    if [ -n "$gitstat" ]; then
+	local lin1="${gitstat%%$'\n'*}"   
+	local bnam="${lin1#'## '}"      # branchname
+	bnam="${bnam%%'...'*}"          # finish extraction
+	local bcol="$X1_COLG0"          # branch color
+	if [ "${lin1%'[ahead '*}" != "$lin1" ] || \
+	   [ "${lin1%'[behind '*}" != "$lin1" ]; then
+	    bcol="$X1_COLC" # ahead/behind of remote, cyan
+	fi
+	lin1="${gitstat/"$lin1"/}" # remove lin1 from gitstat
+	gitstat="$X1_COLG0($X1_ECOL"
+	if [ "${lin1:1:2}" = '??' ]; then # Untracked
+	    bcol="$X1_COLY"
+	elif [ "${#lin1}" -gt 0 ]; then   # Dirty
+	    bcol="$X1_COLR"
+	fi
+	gitstat="$gitstat$bcol$bnam$X1_ECOL$X1_COLG0)$X1_ECOL"
     fi
 
-    local gsep="$X1_COLG0|$X1_ECOL"             # green vert
-    local user="$X1_COLG0\u@$X1_ECOL"           # green user
+    # Check for a conda environment
+    local condaenv=''
+    [ -n "$CONDA_PREFIX" ] && condaenv="(${CONDA_PREFIX##*/})"
+
+    # Only use current working dir if in tmux
+    [ -z "$TMUX" ] && x1_PWD "$PWD" || 	X1_DISPPWD='\W'
+
+    #check if we're in an ssh session
+    local host=''
+    [ -n "$SSH_CLIENT" ] && host="$X1_COLG" || host="$X1_COLG0"
+    host="$host\h$X1_ECOL"
+
+    # Build the PS1 
     local dispdir="$X1_COLB$X1_DISPPWD$X1_ECOL" # blue pwd
-    PS1="$user$host$gsep$x1time$gsep$dispdir\$$stat> "
+    local user="$condaenv$X1_COLG0@$X1_ECOL"
+    if [ -z "$gitstat" ] && [ -z "$condaenv" ]; then
+	user="$X1_COLG0\u@$X1_ECOL"            # green user
+	[ -z "$x1time" ] &&\
+	    x1time="$X1_COLG0\A$X1_ECOL$gsep" # green clock
+    fi
+
+    PS1="$user$host$gitstat$gsep$x1time$dispdir\\\$$stat> "
     #echo "$user$host$gsep$time$gsep$dispdir\$$stat> "
 }
 PROMPT_COMMAND=x1_get_PS1
